apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: istio-tls
  namespace: istio-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: hello-world-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tlscrt | b64dec }}"
        tls.key: "{{ .tlskey | b64dec }}"
  data:
    - secretKey: tlscrt
      remoteRef:
        key: hello-world/dev/istio-tls
        property: tls.crt
    - secretKey: tlskey
      remoteRef:
        key: hello-world/dev/istio-tls
        property: tls.key